apiVersion: kubescheduler.config.k8s.io/v1
kind: KubeSchedulerConfiguration
extenders:
- urlPrefix: "http://127.0.0.1:8080/"
filterVerb: filter
prioritizeVerb: prioritize
weight: 1
enableHTTPS: false
nodeCacheCapable: false
ignorable: true
httpTimeout: 15s
leaderElection:
leaderElect: true
clientConnection:
kubeconfig: /etc/kubernetes/scheduler.conf